server:
  port: 8480
spring:
  application:
    name: api-gateway
  cloud:
     gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*" 
      routes:
        - id: owner-service
          uri: lb://owner-service:8180
          predicates:
            - Path=/owner/**,/validPet/**
          filters:
            - name: CircuitBreaker
              args:
                name: owner-service
                fallbackuri: forward:/ownerServiceFallback
        - id: vet-service
          uri: lb://vet-service:8280
          predicates:
            - Path=/speciality/**,/vet/**
          filters:
            - name: CircuitBreaker
              args:
                name: vet-service
                fallbackuri: forward:/vetServiceFallback
        - id: visit-service
          uri: lb://visit-service:8380
          predicates:
            - Path=/pet/**,/visit/**
          filters:
            - name: CircuitBreaker
              args:
                name: visit-service
                fallbackuri: forward:/visitServiceFallback

# Eureka Client
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}